"""add timestamp to each trial (Performance)

Revision ID: 062aa076bfa6
Revises: 7576f76db98b
Create Date: 2018-10-03 22:51:49.640188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062aa076bfa6'
down_revision = '7576f76db98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('performance', 'timestamp')
    # ### end Alembic commands ###
